apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicure-deployment
  labels:
    app: medicure-deploy-lbl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: medicure-deployment
  template:
    metadata:
      labels:
        app: medicure-deployment
    spec:
      containers:
      - name: medicure-app-container
        image: gopal3010/medicure:latest 
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: medicure-np-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000
    nodeport: 30001
selector:
  app: medicure-deployment

